# Site settings
title: Provincie Noord-Holland Data Lab
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Het Provincie Noord-Holland Data Lab is een omgeving voor het Connected Data innovatie project

timezone: Europe/Amsterdam
  
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://provincienh.github.io" # the base hostname & protocol for your site
github_username:  ProvincieNH

# Build settings
markdown: kramdown
